SMSService/Controllers/GroupListController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMSService.Models;
using SMSService.Reports;

namespace SMSService.Controllers
{
    public class GroupListController : Controller
    {
        // GET: GroupList

        //=============================================View Page==========================================
        public ActionResult GroupNamewiseList()
        {

            using (SMSServiceEntities db = new SMSServiceEntities())
            {
                try
                {
                    ViewBag.GroupName = db.BulkSMSListNames.ToList();
                    return View();
                }
                catch (Exception ex)
                {

                    throw ex;
                }
            }

        }
        //=============================================View Page End======================================
        public ActionResult GroupNamewiseListPartialView(int listNameId)
        {

            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    List<BulkSMSNumberList> model = new List<BulkSMSNumberList>();
                    model = GetGroupNumberList(listNameId);
                    return PartialView("_GroupNamewiseListPartialView", model);


                }


            }
            catch (Exception ex)
            {

                throw ex;
            }



        }
        public ActionResult GroupNamewiseListEditPartialView(int id)
        {

            try
            {
                SMSServiceEntities db = new SMSServiceEntities();

                BulkSMSNumberList model = db.BulkSMSNumberLists.Find(id);
                if (model != null)
                {
                    ViewBag.ListName = db.BulkSMSListNames.ToList();


                }
                return PartialView("_GroupNamewiseListEditPartialView", model);





            }
            catch (Exception ex)
            {

                throw ex;
            }



        }
        //=============================================Partial View Page==================================

        //=============================================Partial View Page End==============================

        //=============================================Jason Action=======================================
        public ActionResult DownloadList(int listNameId, string type)
        {

            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    bool result = false;
                    var name = "";
                    var bulkSmsListName = db.BulkSMSListNames.FirstOrDefault(x => x.ListNameID == listNameId);
                    if (bulkSmsListName != null)
                    {
                         name = bulkSmsListName.ListName??"";
                    }
                    List<BulkSMSNumberList> model = new List<BulkSMSNumberList>();
                    model = GetGroupNumberList(listNameId);
                    if (model.Any())
                    {
                        if (type == "Excel")
                        {
                            ExcelReports ep = new ExcelReports();
                           
                            if (ep.ListToExcel(model))
                            {
                                return Json("", JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                Type officeType = Type.GetTypeFromProgID("Excel.Application");
                                if (officeType == null)
                                {
                                    return Json("You have no MS-Excel installed!", JsonRequestBehavior.AllowGet);
                                }
                                else
                                {
                                    return Json("Try Again!", JsonRequestBehavior.AllowGet);
                                }
                            }
                            

                        }
                        else if(type == "CSV")
                        {
                            CsvReports cs=new CsvReports();
                            if (cs.ListToCsv(model, name))
                            {
                                return Json("Download Successfully Completed! See Your Desktop.", JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                return Json("Try Again!", JsonRequestBehavior.AllowGet);
                            }
                        }


                        return Json("", JsonRequestBehavior.AllowGet);

                    }
                    else
                    {
                        return Json("No data available!", JsonRequestBehavior.AllowGet);
                    }
                }


            }
            catch (Exception ex)
            {

                throw ex;
            }



        }

        //=============================================Jason Action End===================================

        //=============================================Post  Method======================================
        //=============================================Post  Method======================================

        //=============================================Get  Method=======================================
        public List<BulkSMSNumberList> GetGroupNumberList(int listNameId)
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    List<BulkSMSNumberList> model = new List<BulkSMSNumberList>();

                    if (listNameId > 0)
                    {
                        var ml = db.BulkSMSNumberLists.Where(x => x.ListNameID == listNameId).ToList();
                        foreach (var l in ml)
                        {
                            BulkSMSNumberList gl = new BulkSMSNumberList();
                            gl.ID = l.ID;
                            gl.MobileNumber = l.MobileNumber;
                            gl.EntryDate = l.EntryDate;
                            gl.ListNameID = l.ListNameID;
                            model.Add(gl);
                        }
                    }

                    return model;

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }


        }//
        //=============================================Get  Method=======================================

        //=============================================Edit  Method======================================
        public ActionResult UpdateList(BulkSMSNumberList model)
        {
            using (SMSServiceEntities db = new SMSServiceEntities())
            {
                try
                {
                    BulkSMSNumberList m = db.BulkSMSNumberLists.Find(model.ID);
                    if (m != null)
                    {
                        m.ListNameID = model.ListNameID;
                        m.MobileNumber = model.MobileNumber;
                        m.EntryDate = DateTime.Now.ToString(CultureInfo.InvariantCulture);
                        db.SaveChanges();
                    }
                    return RedirectToAction("GroupNamewiseList");

                }
                catch (Exception ex)
                {

                    throw ex;
                }
            }

        }
        //=============================================Edit  Method End==================================

        //=============================================Update  Method====================================
        public ActionResult GroupItemDelete(int id)
        {
            using (SMSServiceEntities db = new SMSServiceEntities())
            {

                try
                {
                    BulkSMSNumberList find = db.BulkSMSNumberLists.Find(id);
                    if (find != null)
                    {
                        db.BulkSMSNumberLists.Remove(find);
                        db.SaveChanges();
                        return Json("Remove Successfully!", JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json("Item Not Found! Try Again.", JsonRequestBehavior.AllowGet);
                    }

                }
                catch (Exception ex)
                {

                    throw ex;
                }
            }

        }
        //=============================================Update  Method End================================

        //=============================================Delete  Method====================================
        //=============================================Delete  Method End================================
    }
}

SMSService/Views/GroupList/GroupNamewiseList.cshtml
@{
    ViewBag.Title = "List Show";
    Layout = "~/Views/Shared/Sms_Layout.cshtml";
}
<style>
    .wrapper-content {
        padding: 10px 10px 10px;
    }
</style>
<!----------------------Loader Image------------------------------------>
<div style="z-index: 101; width: 100%; height: 100%; background-color: rgba(40, 30, 20, 0.4); position: absolute; text-align: center; display: none;" id="loaderImageDiv">
    <img style="width: 80px; position: absolute; z-index: 102; height: 80px; left: 40%; top: 35%;" src="~/Content/image/InternetSlowdown_Day.gif" />
</div>
<!------------------------------Menue Start--------------------------------->
<div style="width: 100%; margin:2px auto; " class="wrapper wrapper-content animated fadeInRight">
    <div class="row" style="margin-right:6%;">
        <div class="col-md-7">
            <ol class="breadcrumb">
                <li>
                    <a>Group Setup</a>
                </li>
                <li class="active">
                    <b>GroupNamewiseList</b>
                </li>
            </ol>
        </div>
        <div class="col-md-5">

        </div>
    </div>
</div>
<!------------------------------Menue End--------------------------------->
<!------------------------------Main Body Start--------------------------->
<div style="width: 85%; margin: 0 auto" class="wrapper wrapper-content animated fadeInRight">
    <div class="row well">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @Html.DropDownList("listNameId", new SelectList(ViewBag.GroupName, "ListNameID", "ListName"), "--Select List --", new {@class = "form-control", @onchange = "ListNameOnChange()"})
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div id="resultList"></div>
    </div>
</div>

<!--Modal Start-->


<div class="modal fade" id="EditModalShow" role="dialog">
    <div style="border-radius: 10px; width:50%;" class="modal-dialog modal-md">
        <div style="background-color: white;" class="modal-content">
            <div class="modal-header">
                <label style="font-size: 20px;" id="ModalTitle"></label>
                <a href="#" data-dismiss="modal" class="pull-right" style="color: #dcdcdc"><i class="fa fa-times"></i></a>
            </div>
            <div id="EditModalResult" class="modal-body">
                Test
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="DeleteModalShow" role="dialog">
    <div style="border-radius: 10px; width:50%;" class="modal-dialog modal-md">
        <div style="background-color: white;" class="modal-content">
            <div class="modal-header">
                <label style="font-size: 20px;" id="ModalTitle"></label>
                <a href="#" data-dismiss="modal" class="pull-right" style="color: #dcdcdc"><i class="fa fa-times"></i></a>
            </div>
            <div class="modal-body">
                <input type="hidden" id="GroupListItemIdHidden"/>
                <span style="font-size: 18px;font-weight:bold">Are you sure to delete <span id="GroupnumberSapn"></span> from List?</span>
            </div>
            <div class="modal-footer">
                <a onclick="DeleteConfirm()"  class="btn btn-warning">OK</a>
                <a href="#" data-dismiss="modal" class="btn btn-danger" >Cancel</a> 
            </div>
        </div>
    </div>
</div>


<!--Modal End-->

<!---------------------------------Script Start----------------------------------->

@section scriptsMenu{
    <script>

        $(document).ready(function () {

            if ($("#GroupSMSMainMenu").length > 0) {
                $("#GroupSMSMainMenu").addClass("active");
                $("#GroupNamewiseListSubmnue").attr("class", "active");

            }


        });

    </script>
}


@section scripts
{

    <script>

        function ListNameOnChange() {
            var id = $("#listNameId").val();
            $("#loaderImageDiv").show();
            if (id != "") {
                $.ajax({
                    type: "GET",
                    url: "/GroupList/GroupNamewiseListPartialView",
                    data: { listNameId: id },
                    success: function (response) {
                        //alert(response);
                        $("#loaderImageDiv").hide();
                        $("#resultList").html("");
                        $("#resultList").append(response);
                        //$("#loaderImageDiv").hide();
                    }
                });
            }
        }

        function GroupNumberEdit(id) {
            if (id != "") {
                $.ajax({
                    type: "GET",
                    url: "/GroupList/GroupNamewiseListEditPartialView",
                    data: { id: id },
                    success: function (response) {
                        //alert(response);
                        $("#EditModalResult").html("");
                        $("#EditModalResult").append(response);
                        //$("#loaderImageDiv").hide();
                    }
                }).then($("#EditModalShow").modal("show"));
            }

          
        }
        function GroupNumberDelete(id, number) {
            var a = number.toString();
           // alert(a);
            $("#GroupListItemIdHidden").val("");
            $("#GroupListItemIdHidden").val(id);

            $("#GroupnumberSapn").html("");
            $("#GroupnumberSapn").append(a);
            
            $("#DeleteModalShow").modal("show");

        }
        function DeleteConfirm(){
            var gid = $("#GroupListItemIdHidden").val();
        
            if (gid != "") {
                $.ajax({
                    type: "GET",
                    url: "/GroupList/GroupItemDelete",
                    data: { id: gid },
                    success: function (response) {
                        $("#DeleteModalShow").modal("hide");
                        alert(response);
                        ListNameOnChange();
                    }
                });
            }


        }
        //======================Download Excel file =========================
        function DownloadExcelFile() {
            var id = $("#listNameId").val();
            //alert(id);
            if (id != "") {
                $.ajax({
                    type: "GET",
                    url: "/GroupList/DownloadList",
                    data: { listNameId: id, type:"Excel" },
                    success: function (response) {
                        if (response != "") {
                            alert(response);
                        }
                       
                        
                    }
                });
            }
        }
        //======================Download CSV file =========================
        function DownloadCSVFile() {
            var id = $("#listNameId").val();
            //alert(id);
            if (id != "") {
                $.ajax({
                    type: "GET",
                    url: "/GroupList/DownloadList",
                    data: { listNameId: id, type: "CSV" },
                    success: function (response) {
                        if (response != "") {
                            alert(response);
                        }


                    }
                });
            }
        }
    </script>
}

SMSService/Views/GroupList/_GroupNamewiseListEditPartialView.cshtml
@model SMSService.Models.BulkSMSNumberList

@using (Html.BeginForm("UpdateList", "GroupList"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.ListNameID, "ListName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.ListNameID, new SelectList(ViewBag.ListName, "ListNameID", "ListName", Model.ListNameID), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ListNameID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}

SMSService/Views/GroupList/_GroupNamewiseListPartialView.cshtml
@model IEnumerable<SMSService.Models.BulkSMSNumberList>
@{
    int a = 1;
}

@if (!Model.Any())
{
    <div class="card">
        <p style="font-weight: bolder; text-align: center; color: red;"> No Data Found!</p>
    </div>
}
else
{
    <div style="margin-bottom:10px;">
        <a title="Excel File Download" style="margin-left: 5px;" onclick="DownloadExcelFile()" class="btn-sm btn-default pull-right"><i class="fa fa-file-excel-o"></i>&nbsp;Excel</a>
        <a title="Excel File Download" style="margin-left: 5px;" onclick="DownloadCSVFile()" class="btn-sm btn-default pull-right"><i class="fa fa-download"></i>&nbsp;Text</a>
    </div>
    <table id="MyDataTable" class="display" style="width: 100%">
        <thead class="btn-success">
            <tr>
                <th>#</th>
                <th>Mobile Number</th>
                <th>EntryDate</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@(a++)</td>
                    <td>@item.MobileNumber</td>
                    <td>@item.EntryDate</td>
                    <td>

                        <a href="#/" class="btn btn-warning" onclick="GroupNumberEdit(@item.ID)" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
                        <a href="#/" class="btn btn-danger" onclick="GroupNumberDelete(@item.ID, '@item.MobileNumber')" title="Delete"><i class="glyphicon glyphicon-trash"></i></a>


                    </td>
                </tr>

            }
            
        </tbody>
    </table>
}

<script type="text/javascript" language="javascript" class="init">


    $(document).ready(function() {
        $('#MyDataTable').DataTable();
    } );


</script>