SMSService/Models/SendSM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendSM
    {
        public int ID { get; set; }
        public string MobileName { get; set; }
        public string Message { get; set; }
        public string SMSSource { get; set; }
        public int Issend { get; set; }
        public string Entrydate { get; set; }
        public string SendingTime { get; set; }
    
        public virtual smsCodeFlag smsCodeFlag { get; set; }
    }
}

SMSService/Controllers/BulkSMSController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using SMSService.Models;
using SMSService.ViewModel;
using static System.Data.Entity.Core.Objects.EntityFunctions;

namespace SMSService.Controllers
{
    public class BulkSMSController : Controller
    {


        //=============================================View Page==========================================
        public ActionResult BulkSmsList()
        {
            return View();
        }


        public ActionResult BulkSMSNumbers()
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    ViewBag.ListName = db.BulkSMSListNames.ToList();
                    return View();
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }


        public ActionResult SmsList()
        {
            return View();
        }

        public ActionResult SendSMS()
        {

            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    ViewBag.BSList = db.BulkSMSListNames.ToList();
                    return View();
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        //=============================================View Page End======================================

        //=============================================Partial View Page==================================

        public ActionResult LoadBulkSmsListName()
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    var BulkSmsNameList = db.BulkSMSListNames.ToList();
                    return PartialView("_LoadBulkSmsListName", BulkSmsNameList);
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }




        public ActionResult SmsListPartial(int isSend,DateTime? fromDate, DateTime? toDate)
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    var rDate = DateTime.Today;
                    TimeSpan time = new TimeSpan(23, 59, 59);
                    
                    //DateTime nFDate;
                    //DateTime nTDate;
                    
                    if (fromDate != null && toDate != null)
                    {
                        DateTime check = (DateTime)toDate;
                        fromDate = (DateTime) fromDate;
                        toDate = check.Add(time);
                    }
                    else
                    {
                        fromDate = rDate;
                        toDate = rDate.Add(time);
                    }

                    string sql = "select * from [dbo].[SendSMS] where Issend="+ isSend + " and Entrydate between CONVERT(date,'"+ fromDate + "') and CONVERT(date,'"+ toDate + "')";
                    var data = db.Database.SqlQuery<SMSSendVm>(sql).ToList();
                    return PartialView("_SmsListPartial", data);
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }


        //=============================================Partial View Page End==============================

        //=============================================Jason Action=======================================
        //=============================================Jason Action End===================================

        //=============================================Post  Method======================================

        
        public ActionResult DeleteListNameAndNumber(int id)
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    var lId = db.BulkSMSListNames.Find(id);
                   var listOfNumber = db.BulkSMSNumberLists.Where(x => x.ListNameID == id).ToList();
                    if (listOfNumber.Any())
                    {
                        db.BulkSMSNumberLists.RemoveRange(listOfNumber);
                        db.SaveChanges();
                    }
                    if (lId != null) db.BulkSMSListNames.Remove(lId);
                    db.SaveChanges();
                   
                    return Json("List Deleted successfully", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                
                throw ex;
            }
        }
        [HttpPost]
        public bool ResendSms(int id)
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    var resendValue = db.SendSMS.FirstOrDefault(x => x.ID == id);
                    resendValue.Issend = 1;
                    db.SaveChanges();
                   return true;
                }
            }
            catch (Exception ex)
            {
                
                throw ex;
            }
        }

        [HttpPost]

        public bool ErrorDeleteData(int id)
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    var valueOfRowDel = db.SendSMS.Find(id);
                    if (valueOfRowDel != null) db.SendSMS.Remove(valueOfRowDel);
                    db.SaveChanges();
                    return true;
                }
            }
            catch (Exception ex)
            {
                
                throw ex;
            }   
        }
        [HttpPost]
        public ActionResult BulkSmsListEntry(string listName, string btnSave, int? listNameId)
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {
                    if (btnSave == "Submit")
                    {
                        if (!string.IsNullOrWhiteSpace(listName))
                        {

                            bool data = db.BulkSMSListNames.Where(x => x.ListName == listName).Any();

                            if (data)
                            {
                                TempData["ErrorMassage"] = "List Name Already Exist";
                            }
                            else
                            {

                                BulkSMSListName bslm = new BulkSMSListName();
                                bslm.ListName = listName;
                                bslm.EntryDate = DateTime.Now.ToString();
                                db.BulkSMSListNames.Add(bslm);
                                db.SaveChanges();
                                TempData["successMassage"] = "Data Saved Successfully!";
                            }

                        }
                        else
                        {
                            TempData["ErrorMassage"] = "Data not Saved! Please try again";
                        }
                    }
                    else if (btnSave == "Update")
                    {
                        if (listNameId != null)
                        {
                            var bSLName = db.BulkSMSListNames.FirstOrDefault(x => x.ListNameID == listNameId);
                            var b = db.BulkSMSListNames.Where(x => x.ListName == listName).Any();
                            if (b)
                            {
                                TempData["ErrorMassage"] = "List Name Already Exist";

                            }
                            else
                            {
                                bSLName.ListName = listName;
                                db.SaveChanges();
                                TempData["successMassage"] = "Data Saved Successfully!";

                            }

                        }
                    }

                    return RedirectToAction("BulkSmsList");

                }
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        [HttpPost]
        public ActionResult BulkSMSNumberListEntry(int? listNameFId, int? listNameNId, HttpPostedFileBase smsNumberFile, string mobileNumber = "")
        {
            try
            {
                using (SMSServiceEntities db = new SMSServiceEntities())
                {

                    if (smsNumberFile != null && listNameFId!=null)
                    {
                        var filePath = "";
                        string fileExtension = Path.GetExtension(smsNumberFile.FileName).ToLower();
                        if (fileExtension == ".txt" || fileExtension == ".csv")
                        {
                            string path = Server.MapPath("~/Uploads/");
                            if (!Directory.Exists(path))
                            {
                                Directory.CreateDirectory(path);
                            }
                            var file = path + Path.GetFileName(smsNumberFile.FileName);
                            filePath = file;
                            smsNumberFile.SaveAs(filePath);
                            string fileData = System.IO.File.ReadAllText(filePath);
                            foreach (string row in fileData.Split('\n'))
                            {
                                if (!string.IsNullOrEmpty(row))
                                {
                                    var mobNumber = "";

SMSService/Views/BulkSMS/BulkSMSNumbers.cshtml
@{
    ViewBag.Title = "Add File";
    Layout = "~/Views/Shared/Sms_Layout.cshtml";
}



<style>
    .wrapper-content {
        padding: 10px 10px 10px;
    }

    .color {
        background-color: white;
        color: black;
    }
</style>
<!----------------------Loader Image------------------------------------>
<div style="z-index: 101; width: 100%; height: 100%; background-color: rgba(40, 30, 20, 0.4); position: absolute; text-align: center; display: none;" id="loaderImageDiv">
    <img style="width: 80px; position: absolute; z-index: 102; height: 80px; left: 40%; top: 35%;" src="~/Content/image/InternetSlowdown_Day.gif" />
</div>
<!------------------------------Menue Start--------------------------------->
<div style="width: 100%; margin:2px auto; " class="wrapper wrapper-content animated fadeInRight">
    <div class="row" style="margin-right:6%;">
        <div class="col-md-7">
            <ol class="breadcrumb">
                <li>
                    <a>Bulk SMS</a>
                </li>
                <li class="active">
                    <b>Bulk SMS List Number</b>
                </li>
            </ol>
        </div>
        <div class="col-md-5">

        </div>
    </div>
</div>
<!------------------------------Menue End--------------------------------->
<!------------------------------Main Body Start--------------------------->
<div style="width: 85%; margin: 0 auto" class="wrapper wrapper-content animated fadeInRight">
    <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" id="addFileBtn" class="btn btn-secondary" value="addFile" onclick="AddFile()">Add File</button>
        <button type="button" id="addNumberBtn" class="btn btn-secondary" value="addNumber" onclick="AddNumber()">Add Number</button>
    </div><br /><br />

    <div id="SuccessOrErrorMessageDiv" style="text-align: center;">
        <label id="successMassage" style="font-size: 20px;" class="label label-success">@TempData["successMassage"]</label>
        <label id="ErrorMassage" style="font-size: 20px;" class="label label-danger">@TempData["ErrorMassage"]</label>
    </div>

    <!--Add CSV/TXT File Part-->
    <div id="FileAddDiv" class="form-horizontal">
        @using (Html.BeginForm("BulkSMSNumberListEntry", "BulkSMS", FormMethod.Post, new { id = "bulkSmsNumberfileEntry", enctype = "multipart/form-data" }))
        {
            <div class="row well">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <label class="col-md-3">List Name</label>
                        <div class="col-md-9 form-group">
                            @Html.DropDownList("listNameFId", new SelectList(ViewBag.ListName, "ListNameID", "ListName"), "Select List Name", new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="row" id="uploadFileDiv">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <label class="col-md-3">Choose File</label>
                        <div class="col-md-9 form-group">
                            <input type="file" class="form-control" name="smsNumberFile" id="smsNumberFile"/>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-4" style="margin-left: 59%;">
                        <a class="btn  btn-default" id="btnClear" onclick="AllClear()"><i class="fa fa-refresh">&nbsp;</i>Refresh</a>
                        <button type="submit" class="btn btn-primary" id="saveButton"><i class="fa fa-save">&nbsp;&nbsp;</i>Save</button>
                    </div>
                </div>
            </div>
        }
    </div>

    <!--Add Mobile Number Part-->
    <div id="MobileNumberAddDiv" class="form-horizontal" style="display: none;">
        @using (Html.BeginForm("BulkSMSNumberListEntry", "BulkSMS", FormMethod.Post, new { id = "bulkSmsNumberListEntry", enctype = "multipart/form-data" }))
        {
            <div class="row well">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <label class="col-md-3">List Name</label>
                        <div class="col-md-9 form-group">
                            @Html.DropDownList("listNameNId", new SelectList(ViewBag.ListName, "ListNameID", "ListName"), "Select List Name", new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="row" id="uploadFileDiv">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <label class="col-md-3">Mobile Number</label>
                        <div class="col-md-9 form-group">
                            <input type="text" id="mobileNumber" name="mobileNumber" class="form-control" placeholder="Enter Mobile Number"/>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-4" style="margin-left: 59%;">
                        <a class="btn  btn-default" id="btnClear" onclick="AllClear()"><i class="fa fa-refresh">&nbsp;</i>Refresh</a>
                        <button type="submit" class="btn btn-primary" id="saveButton"><i class="fa fa-save">&nbsp;&nbsp;</i>Save</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<!---------------------------------Script Start----------------------------------->

@section scriptsMenu{
    <script>

        $(document).ready(function () {

            if ($("#GroupSMSMainMenu").length > 0) {
                $("#GroupSMSMainMenu").addClass("active");
                $("#AddFileSubmnue").attr("class", "active");

            }


        });

    </script>
}


@section scripts
{

    <script>
        $(document).ready(function () {
            $("#loaderImageDiv").hide();
            AddFile();
        });

        function AddColor(btnValue) {
            if (btnValue == "addFile") {
                $("#addNumberBtn").removeClass('color');
                $("#addFileBtn").addClass('color');
            }
            if (btnValue == "addNumber") {
                $("#addFileBtn").removeClass('color');
                $("#addNumberBtn").addClass('color');
            }
        }

        $("#bulkSmsNumberListEntry").submit(function (e) {
            var mobileNumber = $("#mobileNumber").val();
            var listNameId = $("#listNameNId").val();

            if (listNameId == "") {
                alert("Please Select Mobile Number List Name");
                $("#listNameNId").focus();
                e.preventDefault();
            } else if (mobileNumber == "") {
                alert("Please Enter Mobile Number");
                $("#mobileNumber").focus();
                e.preventDefault();
            }
            $("#loaderImageDiv").show();
        });

        $("#bulkSmsNumberfileEntry").submit(function (e) {
            var fileLoader = $("#smsNumberFile").val();
            var listNameId = $("#listNameFId").val();

            if (listNameId == "") {
                alert("Please Select Mobile Number List Name");
                $("#listNameFId").focus();
                e.preventDefault();
            } else if (fileLoader == "") {
                alert("Please Upload CSV/TXT file");
                $("#smsNumberFile").focus();
                e.preventDefault();
            }
            $("#loaderImageDiv").show();
        });


        function AddFile() {
            var btnValue = $("#addFileBtn").val();
            AddColor(btnValue);
            $("#MobileNumberAddDiv").hide();
            $("#FileAddDiv").show();


        } function AddNumber() {
            var btnValue = $("#addNumberBtn").val();
            AddColor(btnValue);
            $("#FileAddDiv").hide();
            $("#MobileNumberAddDiv").show();

        }

        $("#SuccessOrErrorMessageDiv").toggle(3000);

        function AllClear() {
            $("#listNameFId").val("");
            $("#listNameNId").val("");
            $("#mobileNumber").val("");
            $("#smsNumberFile").val("");
        }
    </script>
}

SMSService/Views/BulkSMS/BulkSmsList.cshtml
@model SMSService.Models.BulkSMSListName
@{
    ViewBag.Title = "Group Name";
    Layout = "~/Views/Shared/Sms_Layout.cshtml";
}


<style>
    .wrapper-content {
        padding: 10px 10px 10px;
    }
</style>
<!----------------------Loader Image------------------------------------>
<div style="z-index: 101; width: 100%; height: 100%; background-color: rgba(40, 30, 20, 0.4); position: absolute; text-align: center; display: none;" id="loaderImageDiv">
    <img style="width: 80px; position: absolute; z-index: 102; height: 80px; left: 40%; top: 35%;" src="~/Content/image/InternetSlowdown_Day.gif" />
</div>
<!------------------------------Menue Start--------------------------------->
<div style="width: 100%; margin:2px auto; " class="wrapper wrapper-content animated fadeInRight">
    <div class="row" style="margin-right:6%;">
        <div class="col-md-7">
            <ol class="breadcrumb">
                <li>
                    <a>Bulk SMS</a>
                </li>
                <li class="active">
                    <b>Bulk SMS List Entry</b>
                </li>
            </ol>
        </div>
        <div class="col-md-5">

        </div>
    </div>
</div>
<!------------------------------Menue End--------------------------------->
<!------------------------------Main Body Start--------------------------->
<div style="width: 85%; margin: 0 auto" class="wrapper wrapper-content animated fadeInRight">
    <div id="SuccessOrErrorMessageDiv" style="text-align: center;">
        <label id="successMassage" style="font-size: 20px;" class="label label-success">@TempData["successMassage"]</label>
        <label id="ErrorMassage" style="font-size: 20px;" class="label label-danger">@TempData["ErrorMassage"]</label>
    </div>
    @using (Html.BeginForm("BulkSmsListEntry", "BulkSMS", FormMethod.Post, new { id = "bulkSmsListEntry" }))
    {
        <div class="row well">
            <div class="col-md-7">
                <label class="col-md-4">SMS List Name</label>
                <div class="col-md-8">
                    <input type="text" id="listName" name="listName" class="form-control" placeholder="SMS List Name" />
                </div>
            </div>
            <div class="col-md-5">
                <input type="submit" name="btnSave" class="btn btn-primary" id="saveButton" value="Submit" />
                <button type="button" class="btn btn-default" onclick="ClearFunc()"><i class="fa fa-refresh">&nbsp;</i>Refresh</button>
            </div>
        </div>

    }
    <br />
    <div id="LoadPartialView"></div>

</div>

<!--Modal Start-->

<div class="modal fade" id="DeleteModalShow" role="dialog">
    <div style="border-radius: 10px; width:50%;" class="modal-dialog modal-md">
        <div style="background-color: white;" class="modal-content">
            <div class="modal-header">
                <label style="font-size: 20px;" id="ModalTitle"></label>
                <a href="#" data-dismiss="modal" class="pull-right" style="color: #dcdcdc;"><i class="fa fa-times"></i></a>
            </div>
            <div class="modal-body">
                <input type="hidden" id="ListItemIdHidden" />
                <span style="font-size: 18px; font-weight: bold; color: red;">Are you sure to delete "<span id="GroupNameSapn" style="color: black;"></span><span style="color: black;">&nbsp;&amp;&nbsp;Numbers</span>" from List?</span>
            </div>
            <div class="modal-footer">
                <a onclick="DeleteConfirm()" class="btn btn-warning">OK</a>
                <a href="#" data-dismiss="modal" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </div>
</div>
<!---------------------------------Script Start----------------------------------->

@section scriptsMenu{
    <script>

        $(document).ready(function () {

            if ($("#GroupSMSMainMenu").length > 0) {
                $("#GroupSMSMainMenu").addClass("active");
                $("#AddGroupNameSubmnue").attr("class", "active");

            }


        });

    </script>
}


@section scripts
{

    <script>
        $(document).ready(function () {
            loadBulkSmsList();
        });
        $("#SuccessOrErrorMessageDiv").toggle(3000);

        $("#bulkSmsListEntry").submit(function (e) {
            var listName = $("#listName").val();
            if (listName == "") {
                alert("Please Enter SMS List Name");
                $("#listName").focus();
                e.preventDefault();
            }
        });

        function loadBulkSmsList() {
            $("#loaderImageDiv").show();
            $('#listNameTable').DataTable();
            $.ajax({
                type: "GET",
                url: "/BulkSMS/LoadBulkSmsListName",
                success: function (response) {
                    //alert(response);
                    $("#loaderImageDiv").hide();
                    $("#LoadPartialView").html("");
                    $("#LoadPartialView").append(response);
                }
            });
        }

        function EditList(id) {
            $.ajax({
                type: "GET",
                data: { id: id },
                url: "/BulkSMS/EditList",
                success: function (response) {
                    $("#listName").val(response.listname);
                    $("#listNameId").val(response.listId);
                    $("#saveButton").val("Update");
                }
            });

        }

        function DeleteList(id, listName) {
            var a = listName.toString();
            $("#ListItemIdHidden").val("");
            $("#ListItemIdHidden").val(id);

            $("#GroupNameSapn").html("");
            $("#GroupNameSapn").append(a);

            $("#DeleteModalShow").modal("show");
            
        }

        function DeleteConfirm() {
            var listId = $("#ListItemIdHidden").val();
            //alert(listId);
            if (listId != "") {
                $.ajax({
                    type: "POST",
                    url: "/BulkSMS/DeleteListNameAndNumber",
                    data: { id: listId },
                    success: function (response) {
                        $("#DeleteModalShow").modal("hide");
                        alert(response);
                        loadBulkSmsList();
                    }
                });
            }
        }

        function ClearFunc()
        {
            $("#listName").val("");
            $("#listNameId").val("");
            $("#saveButton").val("Submit");
        }
    </script>
}

SMSService/Views/BulkSMS/_LoadBulkSmsListName.cshtml
@model IEnumerable<SMSService.Models.BulkSMSListName>
@{
    int a = 1;
}
@if (Model.Any())
{
    <table class="display" id="listNameTable">
        <thead class="btn-success">
            <tr >
                <th>#</th>
                <th>List Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in Model)
            {
                <tr>
                    <td>@(a++)</td>
                    <td>@i.ListName</td>
                    <td>
                        <a href="#" class="btn btn-warning" title="Edit" onclick="EditList(@i.ListNameID)"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a href="#" class="btn btn-danger" title="Delete" onclick="DeleteList(@i.ListNameID,'@i.ListName')"><i class="glyphicon glyphicon-trash"></i> </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="row">
        <p style="color: red; text-align: center;">No Data Found!</p>
    </div>
}

<script type="text/javascript" language="javascript" class="init">


    $(document).ready(function () {
        $('#listNameTable').DataTable();
    });


</script>

SMSService/Views/BulkSMS/_SmsListPartial.cshtml
@model IEnumerable<SMSService.ViewModel.SMSSendVm>
@{
    int a = 1;
}
@*<link href="~/DataTables-1.10.18/css/jquery.dataTables.css" rel="stylesheet"/>
<link href="~/DataTables-1.10.18/css/shCore.css" rel="stylesheet"/>
<link href="~/DataTables-1.10.18/css/demo.css" rel="stylesheet" />*@

    @if (!Model.Any())
    {
        <div class="card">
            <p style="font-weight: bolder; text-align: center; color: red;"> No Data Found!</p>
        </div>
    }
    else
    {
        @*<div class="demo-html"></div>*@
        <table id="MyDataTable" class="display" style="width: 100%">
            <thead class="btn-success">
                <tr>
                    <th>#</th>
                    <th>Mobile Number</th>
                    <th>Message</th>
                    <th>SMS Source</th>
                    <th>EntryDate</th>
                    <th>Sending Time</th>
                    <th id="actionColumn">Action</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@(a++)</td>
                    <td>@item.MobileName</td>
                    <td>@item.Message</td>
                    <td>@item.SMSSource</td>
                    <td>@item.Entrydate</td>
                    <td>@item.SendingTime</td>
                    <td>
                        @if (item.Issend == 3)
                        {
                            <a href="#" class="btn btn-primary" title="Resend" onclick="ResendFunc(@item.ID)"><i class="fa fa-send"></i></a>
                            <a href="#" class="btn btn-danger" title="Delete" onclick="DeleteFunc(@item.ID,'@item.MobileName')"><i class="fa fa-trash"></i></a>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }


@*<script src="~/DataTables-1.10.18/js/jquery.dataTables.js"></script>
<script src="~/DataTables-1.10.18/js/shCore.js"></script>
<script src="~/DataTables-1.10.18/js/demo.js"></script>*@
<script type="text/javascript" language="javascript" class="init">


$(document).ready(function() {
    $('#MyDataTable').DataTable();
} );


</script>